name: Atualizar idade no README

on:
  schedule:
    - cron: '0 0 * * *' # Roda todo dia à meia-noite UTC
  workflow_dispatch: # Também pode ser rodado manualmente

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Calcular idade e atualizar README
        run: |
          DATA_NASCIMENTO="2009-07-22"
          HOJE=$(date +%Y-%m-%d)
          IDADE=$(($(date -d "$HOJE" +%Y) - $(date -d "$DATA_NASCIMENTO" +%Y)))

          # Se ainda não fez aniversário este ano, subtrai 1
          if [ "$(date -d "$HOJE" +%m%d)" -lt "$(date -d "$DATA_NASCIMENTO" +%m%d)" ]; then
            IDADE=$((IDADE - 1))
          fi

          sed -i "s/{{IDADE}}/${IDADE}/g" README.md

      - name: Commit e push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualiza idade automaticamente"
          git push
