name: Atualizar Idade no README

on:
  schedule:
    - cron: '0 0 * * *'  # Executa diariamente à meia-noite (UTC)
  workflow_dispatch:     # Permite execução manual pelo GitHub

jobs:
  atualizar-idade:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Calcular idade e atualizar README
        run: |
          DATA_NASCIMENTO="2009-07-22"
          HOJE=$(date +'%Y-%m-%d')
          IDADE=$(($(date -d "$HOJE" +%s) - $(date -d "$DATA_NASCIMENTO" +%s)))
          ANOS=$((IDADE / 31556952))
          sed -i "s/Idade: .*$/Idade: $ANOS anos/" README.md

      - name: Commit e Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Atualiza idade automaticamente no README" || echo "Nada para commitar"
          git push
